### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getEditorState' of undefined

### ISSUE THREAD

**Issue by ahmadseleem** [t9md/atom-vim-mode-visual-block#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.11
**Thrown From**: [vim-mode-visual-block](https://github.com/t9md/atom-vim-mode-visual-block) package, v0.2.9
### Stack Trace

Uncaught TypeError: Cannot read property 'getEditorState' of undefined

```
At /Users/ahmad/.atom/packages/vim-mode-visual-block/lib/main.coffee:44

TypeError: Cannot read property 'getEditorState' of undefined
  at Object.module.exports.getVimEditorState (/Users/ahmad/.atom/packages/vim-mode-visual-block/lib/main.coffee:44:20)
  at Object.module.exports.blockOperation (/Users/ahmad/.atom/packages/vim-mode-visual-block/lib/main.coffee:53:17)
  at atom-text-editor.blockwiseCommands.(anonymous function) (/Users/ahmad/.atom/packages/vim-mode-visual-block/lib/main.coffee:23:47)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at KeymapManager.module.exports.KeymapManager.terminatePendingState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:498:14)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:374:23)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
 36x -0:08.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  6x -0:05.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:04.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:03.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:02.5.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:02.2.0 vim-mode:activate-characterwise-visual-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:01.8.0 vim-mode-visual-block:j (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:01.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:01.4.0 vim-mode-visual-block:j (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:01.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:01.3.0 vim-mode-visual-block:j (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:01.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:01.2.0 vim-mode-visual-block:j (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:01.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:00.2.0 vim-mode-visual-block:j (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:00.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "mac-github-syntax"
    ],
    "disabledPackages": [
      "swift-playground",
      "wrap-lines",
      "toggle-tabs",
      "toggle-tabs",
      "coffee-navigator",
      "linter-ruby",
      "ex-mode"
    ],
    "destroyEmptyPanes": false,
    "projectHome": "/User/ahmad/Documents",
    "ignoredNames": [
      ".DS_Store"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
file-icons, v1.5.8
file-types, v0.5.1
grammar-mode, v1.1.0
haskell-grammar, v0.4.0
highlight-line, v0.11.0
language-chef, v0.5.0
language-elm, v0.5.0
language-haml, v0.21.0
language-haskell, v1.2.0
language-lisp, v0.1.2
language-racket, v0.4.0
language-scheme, v1.4.0
language-smalltalk, v1.0.2
language-sml, v0.3.0
language-swift, v0.4.0
language-viml, v0.2.0
linter, v1.2.4
linter-coffeescript, v1.0.0
linter-ruby-reek, v1.2.0
mac-github-syntax, v1.3.9
minitest-snippets, v0.2.0
tabs-to-spaces, v0.11.0
terminal-panel, v1.14.1
vim-mode, v0.57.0
vim-mode-visual-block, v0.2.9
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by bronson** [comment]
I just received one too.  Just about exactly the same backtrace.

**Comment by t9md** [comment]
The cause was `@vimModeService` was `undefined` at very first activated timing.
So as quick fix, disabled `activationCommands`.
Seem to disappear this issue.
Want to check.

I'm not sure why this happen, how can serviceConsumer(this package) assure consumingService(vim-mode) is available on startup.

Need investigation, further maybe something change on Atom or vim-mode side?

**Comment by bronson** [comment]
I remember some people talking about it on Slack...  Something about how package startup order is nondeterministic so you need to add an event listener to watch for the package you need to be activated first...?  Wasn't really paying attention.  :)  Could ask again!

**Comment by gkze** [comment]
bump, same here

**Comment by t9md** [comment]
Yes package activation order is non-deterministic, but my code is not order depending code.
I will look into further.

By the way from when you guys stating to see this issue?
I want to know some hint like `from I updated Atom to v1.0.3` or `from yesterday` or something like that.

**Comment by t9md** [comment]
Oh I forget to mention,

I've already released quick fix, so updating will solve problem.

**Comment by ahmadseleem** [comment]
works!

**Comment by t9md** [comment]
Putting note for future reference for myself.

The timing service-provider's(vim-mode) service is available is just after service-consumer package(vim-mode-visual-block) is activated.
There is short timing gap between acitaveted -> consuming service become available.

So when consumer package(vim-mode-visual-block) try to use service **immediately after activation**.
There is a possibility where vim-mode service still not yet available.
Currently I don't know how to ensure this won't happen.

What I can do is either of following.
- Remove `activationCommands` from package.json to avoid activation and immediate use situation.
- Use appropriate `activationCommands` if available, in this case `"vim-mode:activate-blockwise-visual-mode"` is right command to kick vim-mode-visual-block package.

~~I chose latter~~.
[Updated] I chose former.
Currently vim-mode not explicitly set vim-mode's `@submode` on text-editor element.
`@submode` keep `linewise`, `blockwise`, `characterwise`.

So we can not currently set keymap on only `vim-mode.visual-mode.blockwise`.
Need to [overload](https://github.com/t9md/atom-vim-mode-visual-block/blob/master/keymaps/vim-mode-visual-block.cson) `atom-text-editor.vim-mode.visual-mode` scope's keymap and use `event.abortKeyBinding()` to delegate to original visual-mode operation.

To choose latter approach change on vim-mode side require to expose `submode` to text-editor element so that keymap selector directly set on that scope.
